// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDQSB1AAq5nbM-qGuHH0QOSZ0H5TLUz1U',
    appId: '1:836573962135:web:9e753896b4e1bcd43eaed2',
    messagingSenderId: '836573962135',
    projectId: 'act12-12e9e',
    authDomain: 'act12-12e9e.firebaseapp.com',
    storageBucket: 'act12-12e9e.firebasestorage.app',
    measurementId: 'G-QK1J2MMF5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBWmrpQ1A8k_AmrzGGzQ5QQK_QNcP2YVg',
    appId: '1:836573962135:android:fcb9ea60442764ce3eaed2',
    messagingSenderId: '836573962135',
    projectId: 'act12-12e9e',
    storageBucket: 'act12-12e9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5lNRHLoiDi-_ra-6x0PgbD3kGCiDw3K4',
    appId: '1:836573962135:ios:aa9f1d974d42a5133eaed2',
    messagingSenderId: '836573962135',
    projectId: 'act12-12e9e',
    storageBucket: 'act12-12e9e.firebasestorage.app',
    iosBundleId: 'com.example.act12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5lNRHLoiDi-_ra-6x0PgbD3kGCiDw3K4',
    appId: '1:836573962135:ios:aa9f1d974d42a5133eaed2',
    messagingSenderId: '836573962135',
    projectId: 'act12-12e9e',
    storageBucket: 'act12-12e9e.firebasestorage.app',
    iosBundleId: 'com.example.act12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDQSB1AAq5nbM-qGuHH0QOSZ0H5TLUz1U',
    appId: '1:836573962135:web:1445d43bcac7831f3eaed2',
    messagingSenderId: '836573962135',
    projectId: 'act12-12e9e',
    authDomain: 'act12-12e9e.firebaseapp.com',
    storageBucket: 'act12-12e9e.firebasestorage.app',
    measurementId: 'G-86HTTVB9Q1',
  );
}
